### ISSUE TITLE
Custom properties

### ISSUE THREAD

**Issue by petterjv** [halloverden/symfony-azure-service-bus-messenger-bundle#4]
Custom properties are not available in the $encodedEnvelope array in the serializer decode method. Is there a reason for this? In our use case the message producer sends metadata using custom properties which we need to decode the message properly.

Is there a way to get hold of them without modifying the bundle code? 

Could it be added? A suggestion is just to add them to the array $encodedEnvelope["customProperties"]

**Comment by tomme87** [comment]
I don't think there is a reason for it, other than I did not think it was necessary at the time.

There is currently no way to get a hold of them in the decode method, but they are in the `AzureServiceBusReceivedStamp`. But I guess it's too late then?

It could be added. Your suggestion seams fine, can you make a PR?

**Comment by petterjv** [comment]
Okay, maybe it's possible to do it with a middleware then. But it still seams reasonable to have it in the encoded envelope in this case. 

I can create a PR.
